#ifndef SCRIPTREPORTENGINE_GLOBAL_H
#define SCRIPTREPORTENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCRIPTREPORTENGINE_LIBRARY)
#  define SCRIPTREPORTENGINE_EXPORT Q_DECL_EXPORT
#else
#  define SCRIPTREPORTENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // ENGINE_GLOBAL_H
